language: python
python:
  - "3.6"

sudo: false

cache: pip

install:
  - pip install -U pip setuptools wheel
  - pip install -r dev.txt -r requirements.txt

script:
  - py.test --cov=. tinyauth
  - flake8 tinyauth

after_success:
  - codecov
